name: reusable workflow
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        type: string
        default: dist
    secrets:
      file-name: 
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact-name}}
      - name: show secrets
        run: echo ${{secrets.file-name}}
      - name: Deploy
        run: ls -al